/**
 * Resource that has to be destroyed manually (textures, tuffers, etc.)
 */
export interface Disposable {
    dispose(): void;
}

export namespace Disposable {
    /**
     * Compose an array of resources into a single disposable object
     */
    export function join(...items: Disposable[]): Disposable {
        return {
            dispose() {
                items.forEach(v => v.dispose());
            },
        };
    }

    export function create<T1 extends Disposable>(create1: () => T1): [T1];

    export function create<T1 extends Disposable, T2 extends Disposable>(
        create1: () => T1,
        create2: (v1: T1) => T2,
    ): [T1, T2];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
    ): [T1, T2, T3];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
    ): [T1, T2, T3, T4];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
    ): [T1, T2, T3, T4, T5];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
    ): [T1, T2, T3, T4, T5, T6];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
    ): [T1, T2, T3, T4, T5, T6, T7];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
    ): [T1, T2, T3, T4, T5, T6, T7, T8];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
    ): [T1, T2, T3, T4, T5, T6, T7, T8, T9];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        T10 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        create10: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => T10,
    ): [T1, T2, T3, T4, T5, T6, T7, T8, T9, T10];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        T10 extends Disposable,
        T11 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        create10: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => T10,
        create11: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
        ) => T11,
    ): [T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        T10 extends Disposable,
        T11 extends Disposable,
        T12 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        create10: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => T10,
        create11: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
        ) => T11,
        create12: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
        ) => T12,
    ): [T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        T10 extends Disposable,
        T11 extends Disposable,
        T12 extends Disposable,
        T13 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        create10: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => T10,
        create11: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
        ) => T11,
        create12: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
        ) => T12,
        create13: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
        ) => T13,
    ): [T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        T10 extends Disposable,
        T11 extends Disposable,
        T12 extends Disposable,
        T13 extends Disposable,
        T14 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        create10: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => T10,
        create11: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
        ) => T11,
        create12: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
        ) => T12,
        create13: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
        ) => T13,
        create14: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
            v13: T13,
        ) => T14,
    ): [T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14];

    export function create<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        T10 extends Disposable,
        T11 extends Disposable,
        T12 extends Disposable,
        T13 extends Disposable,
        T14 extends Disposable,
        T15 extends Disposable,
        T16 extends Disposable,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        create10: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => T10,
        create11: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
        ) => T11,
        create12: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
        ) => T12,
        create13: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
        ) => T13,
        create14: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
            v13: T13,
        ) => T14,
        create15: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
            v13: T13,
            v14: T14,
        ) => T15,
        create16: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
            v13: T13,
            v14: T14,
            v15: T15,
        ) => T16,
    ): [T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16];

    /**
     * Creates multiple disposable resources and returns them as an array in the same order.
     * It is similar to `uses`, but returns the created instances array.
     * If any creator throws, already created resources are disposed in reverse order and the error is rethrown.
     *
     * @example
     * ```ts
     * const [r1, r2] = Disposable.create(
     *   () => createResource1(),
     *   (r1) => createResource2(r1),
     * );
     * // use r1, r2 and dispose them later when appropriate
     * r2.dispose();
     * r1.dispose();
     * ```
     */
    export function create(
        ...functions: ((...parameters: unknown[]) => Disposable)[]
    ): Disposable[] {
        const parameters: Disposable[] = [];
        try {
            for (let i = 0; i < functions.length; i++) {
                parameters.push(functions[i](...parameters));
            }
            return parameters;
        } catch (error) {
            parameters.reverse().forEach(v => v.dispose());
            throw error;
        }
    }

    /**
     * Pass a disposable object into function and destroy it after the call
     *
     * @example
     * ```ts
     * use(texture, (texture) => {
     *     // do something with texture
     * });
     * ```
     */
    export function use<T extends Disposable, R>(
        item: T,
        callback: (item: T) => R,
    ) {
        try {
            return callback(item);
        } finally {
            item.dispose();
        }
    }

    export function uses<T1 extends Disposable, R>(
        create1: () => T1,
        callback: (v1: T1) => R,
    ): R;

    export function uses<T1 extends Disposable, T2 extends Disposable, R>(
        create1: () => T1,
        create2: (v1: T1) => T2,
        callback: (v1: T1, v2: T2) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        callback: (v1: T1, v2: T2, v3: T3) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        callback: (v1: T1, v2: T2, v3: T3, v4: T4) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        callback: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        callback: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        callback: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        callback: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        callback: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        T10 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        create10: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => T10,
        callback: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
        ) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        T10 extends Disposable,
        T11 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        create10: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => T10,
        create11: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
        ) => T11,
        callback: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
        ) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        T10 extends Disposable,
        T11 extends Disposable,
        T12 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        create10: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => T10,
        create11: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
        ) => T11,
        create12: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
        ) => T12,
        callback: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
        ) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        T10 extends Disposable,
        T11 extends Disposable,
        T12 extends Disposable,
        T13 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        create10: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => T10,
        create11: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
        ) => T11,
        create12: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
        ) => T12,
        create13: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
        ) => T13,
        callback: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
            v13: T13,
        ) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        T10 extends Disposable,
        T11 extends Disposable,
        T12 extends Disposable,
        T13 extends Disposable,
        T14 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        create10: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => T10,
        create11: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
        ) => T11,
        create12: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
        ) => T12,
        create13: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
        ) => T13,
        create14: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
            v13: T13,
        ) => T14,
        callback: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
            v13: T13,
            v14: T14,
        ) => R,
    ): R;

    export function uses<
        T1 extends Disposable,
        T2 extends Disposable,
        T3 extends Disposable,
        T4 extends Disposable,
        T5 extends Disposable,
        T6 extends Disposable,
        T7 extends Disposable,
        T8 extends Disposable,
        T9 extends Disposable,
        T10 extends Disposable,
        T11 extends Disposable,
        T12 extends Disposable,
        T13 extends Disposable,
        T14 extends Disposable,
        T15 extends Disposable,
        T16 extends Disposable,
        R,
    >(
        create1: () => T1,
        create2: (v1: T1) => T2,
        create3: (v1: T1, v2: T2) => T3,
        create4: (v1: T1, v2: T2, v3: T3) => T4,
        create5: (v1: T1, v2: T2, v3: T3, v4: T4) => T5,
        create6: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5) => T6,
        create7: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6) => T7,
        create8: (v1: T1, v2: T2, v3: T3, v4: T4, v5: T5, v6: T6, v7: T7) => T8,
        create9: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
        ) => T9,
        create10: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
        ) => T10,
        create11: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
        ) => T11,
        create12: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
        ) => T12,
        create13: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
        ) => T13,
        create14: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
            v13: T13,
        ) => T14,
        create15: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
            v13: T13,
            v14: T14,
        ) => T15,
        create16: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
            v13: T13,
            v14: T14,
            v15: T15,
        ) => T16,
        callback: (
            v1: T1,
            v2: T2,
            v3: T3,
            v4: T4,
            v5: T5,
            v6: T6,
            v7: T7,
            v8: T8,
            v9: T9,
            v10: T10,
            v11: T11,
            v12: T12,
            v13: T13,
            v14: T14,
            v15: T15,
            v16: T16,
        ) => R,
    ): R;

    /**
     * Creates multiple disposable resources, uses them in a callback, and disposes of them afterward.
     * It's similar to the `use` function but allows creating multiple resources.
     *
     * @example
     * ```ts
     * const value = uses(() => createResource1(),
     *   (resource1) => createResource2(resource1),
     *   (resource1, resource2) => computeValue(resource1, resource2));
     * ```
     */
    export function uses(
        ...functions: ((...parameters: unknown[]) => Disposable)[]
    ): unknown {
        const l = functions.length - 1;
        const parameters: Disposable[] = [];
        try {
            for (let i = 0; i < l; i++) {
                parameters.push(functions[i](...parameters));
            }
            return functions[l](...parameters);
        } finally {
            parameters.reverse().forEach(value => value.dispose());
        }
    }
}

export const create = Disposable.create;
export const uses = Disposable.uses;
export const use = Disposable.use;
